// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVu5neIDytD30Sd-bABHD1nv17nwam9-0',
    appId: '1:690749586825:web:831167163951bb2c603558',
    messagingSenderId: '690749586825',
    projectId: 'discount-buddy-d51bf',
    authDomain: 'discount-buddy-d51bf.firebaseapp.com',
    storageBucket: 'discount-buddy-d51bf.firebasestorage.app',
    measurementId: 'G-X0LKXRCGQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7I_MnQ2HhMSEhKDpo2IcB3LzJAOSLnNA',
    appId: '1:690749586825:android:0b5963fa9d801a1c603558',
    messagingSenderId: '690749586825',
    projectId: 'discount-buddy-d51bf',
    storageBucket: 'discount-buddy-d51bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATrEecCiku_ZApXJmJ6Q2cvr4vxvlyASs',
    appId: '1:690749586825:ios:80b06fa46619fe40603558',
    messagingSenderId: '690749586825',
    projectId: 'discount-buddy-d51bf',
    storageBucket: 'discount-buddy-d51bf.firebasestorage.app',
    androidClientId: '690749586825-0c5v33s1k418s14a9pb1krikf0mpo5ph.apps.googleusercontent.com',
    iosClientId: '690749586825-te9jchq8ibjk42uema45kcvl4sarmocc.apps.googleusercontent.com',
    iosBundleId: 'com.ketan.discountbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATrEecCiku_ZApXJmJ6Q2cvr4vxvlyASs',
    appId: '1:690749586825:ios:7619bd79f8fbf096603558',
    messagingSenderId: '690749586825',
    projectId: 'discount-buddy-d51bf',
    storageBucket: 'discount-buddy-d51bf.firebasestorage.app',
    androidClientId: '690749586825-0c5v33s1k418s14a9pb1krikf0mpo5ph.apps.googleusercontent.com',
    iosClientId: '690749586825-stluo4oa20nd9vkv502b6l4n754m0u5k.apps.googleusercontent.com',
    iosBundleId: 'com.discountbuddy.discountBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVu5neIDytD30Sd-bABHD1nv17nwam9-0',
    appId: '1:690749586825:web:9c721f096ce57b4d603558',
    messagingSenderId: '690749586825',
    projectId: 'discount-buddy-d51bf',
    authDomain: 'discount-buddy-d51bf.firebaseapp.com',
    storageBucket: 'discount-buddy-d51bf.firebasestorage.app',
    measurementId: 'G-2JP9MWCB8E',
  );
}
